name: Jobs Demo

on: [push]

jobs:
  build:
    name: Build Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."

  test:
    name: Test Step
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."

  deploy:
    name: deployed
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed started..."
