name: Jobs Demo

on: [push]

jobs:
  build:
    needs: config
    name: Build Step
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."

  config:
    name: config
    runs-on: ubuntu-latest
    steps:
      - run: echo "config..."

  test:
    name: Test Step
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing..."

  deploy:
    name: deployed
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed started..."
